name: Build & Publish

on:
  push:
    branches: [ master ]

jobs:
  worker:
    runs-on: ubuntu-latest

    strategy:
      # some builds might fail, continue if that happens
      fail-fast: false
      # can be tweaked depending on image layer reuse in parallel builds
      max-parallel: 3
      matrix:
        QT_VERSION:
          - 5.15.0
          - 5.14.2
          - 5.13.2
          - 5.12.9
          - 5.11.3
          - 5.10.1
          - 5.9.5

    env:
      IMAGE_NAME: "linuxdeployqt:${{ matrix.QT_VERSION }}"
      GITHUB_IMAGE_NAME: "docker.pkg.github.com/mhitza/docker-linuxdeployqt/linuxdeployqt:${{ matrix.QT_VERSION }}"
      DOCKER_HUB_IMAGE_NAME: "mhitza/linuxdeployqt:${{ matrix.QT_VERSION }}"

    steps:
      - uses: actions/checkout@v2

      - name: login to GitHub docker registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} \
            | docker login https://docker.pkg.github.com -u mhitza --password-stdin

      - name: pull existing image from GitHub registry
        run: |
          docker pull ${{ env.GITHUB_IMAGE_NAME }} || true

      - name: build
        run: |
          docker build \
            --build-arg QT_VERSION=${{ matrix.QT_VERSION }} \
            --cache-from ${{ env.GITHUB_IMAGE_NAME }} \
            -t ${{ env.IMAGE_NAME }} \
            -t ${{ env.GITHUB_IMAGE_NAME }} \
            -t ${{ env.DOCKER_HUB_IMAGE_NAME }} \
            build-context

      - name: push to GitHub registry
        run: |
          docker push ${{ env.GITHUB_IMAGE_NAME }}

      - name: push to Hub.Docker registry
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} \
            | docker login -u mhitza --password-stdin
          docker push ${{ env.DOCKER_HUB_IMAGE_NAME }}
